### ISSUE TITLE
Editor "publishes" book immediately

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#10]

**Comment by shanitajohn** [comment]
Acceptance criteria

- [ ] When a user with appropriate permissions clicks "publish" the item is immediately indexed and goes from being not discoverable to discoverable

**Comment by mark-dce** [comment]
This might just be a "publish" button that immediately changes the access control settings on the monograph and any associated files from it's current state to "Public Access".  For the first pass, we don't even have to worry about whether the item is already "published" - we can handle that level of detail in a separate ticket.
