### ISSUE TITLE
Determine list of initial file metadata fields to display

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#11]
**STORY**
As a user, I would like to see descriptive metadata fields for a file, so that I can understand the context of the file I'm viewing.

**NOTE**
These are probably the same as, or at least very similar to, the [Metadata Template - Objects](https://docs.google.com/spreadsheets/d/12vFKS_ingRqtHaWFmCg52M_d5xwPFGu5r0EAPVERWZs/edit#gid=0) .  So the remaining work is largely determining predicates and identifying data-types and validations if needed.

**ACCEPTANCE**
- [ ] There is an initial list of field names that should be shown on the file-level detail page
- [ ] There is an RDF predicate selected for each field
- [x] Cardinality of fields is listed for each field (i.e. can each field have multiple values, only a single value, or can it be left blank)
- [x] List data type for each field (eg. string, date, integer, decimal, controlled)
- [x] List any validations specific to any fields

**Comment by mark-dce** [comment]
We should try to be clear about what fields can match basic metadata fields elsewhere and what fields can automatically be populated with technical metadata provided by hydra file characterization.
