### ISSUE TITLE
Derivatives creation writing to wrong path

### ISSUE THREAD

**Issue by acozine** [curationexperts/heliotrope#114]
Steps to reproduce:
- [ ] change config/initializers/curation_concerns.rb by setting a different derivatives path, for example, `config.derivatives_path = '/opt/heliotrope/derivatives'`
- [ ] reindex to update existing derivatives (not sure this is necessary)  
- [ ] restart web server  
- [ ] upload a new file  

Expected behavior:  
New derivative is created in the new path defined by curation_concerns.rb

Actual behavior:  
New derivative is created in the default path, which is RAILS_ROOT/tmp/derivatives; application looks for derivative in the new path defined by curation_concerns.rb; monograph show page cannot find thumbnail image and shows a link instead. If you copy the derivative from tmp/derivatives to the new path, the thumbnail appears without reindexing.

**Comment by acozine** [comment]
Per discussion with Justin, opened https://github.com/projecthydra-labs/curation_concerns/issues/691

**Comment by acozine** [comment]
I was able to recreate this issue and fix it simply by restarting resque-pool. 
So: 
Don't need to reindex.
Do need to restart the resque workers after config changes.

**Comment by jmcglone** [comment]
@acozine how do you restart the resque-pool?

**Comment by acozine** [comment]
@jmcglone: on the server, it's `sudo service resque-pool restart`; on a dev environment, you can use one of the rake tasks - e.g. `QUEUE=* VERBOSE=1 rake resque:work`. Make sure redis-server is running before you start up resque workers or a resque-pool.
