### ISSUE TITLE
Deleting the representative file makes a monograph inaccessible

### ISSUE THREAD

**Issue by acozine** [curationexperts/heliotrope#116]
When I delete the representative file from a monograph with multiple files attached, the monograph show page becomes inaccessible.

### Expected behavior: ###

Up for discussion. The system could simply warn me that I cannot delete the representative file, it could automatically fill in another file as the representative, or it could prompt me to choose a replacement representative file. 

### Actual behavior: ###

The monograph appears in search results but when I try to access the show page, I get a 404 error. 

### Steps to reproduce: ###

1. create a monograph with multiple files attached
1. delete the representative file
1. the system redirects to the monograph show page and returns a 404 error
1. return to the main home page and enter an empty search; the monograph is present in search results
1. click on the monograph title, the show page returns a 404 error again

Gist of production log from step 3 above: https://gist.github.com/acozine/89397e058ec044baaf2f

**Comment by mark-dce** [comment]
**ACCEPTANCE** 
If a user happens to delete the file that was selected as the representative for a monograph, the monograph should go back to displaying as if no representative had every been selected (see screenshot below)

**NOTES**
We could do this either by checking if the deleted file had been set as the representative each time we delete a file, or by setting up some kind of default behavior when the representative is missing (404, etc.) or not set.  It feels cleaner to unset the representative, but having a default behavior might be more robust in that it might handle other states and edge cases that we hadn't considered.

**SCREENSHOT**

**Comment by val99erie** [comment]
Note:  If you run monograph.update_index after you delete the representative image, then it behaves properly again.

**Comment by val99erie** [comment]
It's possible that this is related to an issue in hydra-pcdm:
https://github.com/projecthydra-labs/hydra-pcdm/issues/196

**Comment by sethaj** [comment]
This seems like it's working now. I went through the steps to reproduce and didn't get a 404 after deleting the representative file. Instead the monograph page is shown with the X box/default "empty" image, just like in Mark's sample. 

Maybe a curation concerns update fixed this problem?

**Comment by acozine** [comment]
Confirmed fixed. I can no longer reproduce on new monographs or on legacy monographs. Hooray!
