### ISSUE TITLE
Mp3 audio file doesn't play

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#117]
**STEPS TO RECREATE**

- [ ] Search for The Tempest
- [ ] Click on the Tempest 
- [ ] Click on Act 1 Scene 1
- [ ] Click the play button on the media player

**EXPECTED OUTCOME**
Play button is in an active state prior to click. Once clicking on the play arrow audio file plays, sound comes through computer speakers. 

**ACTUAL OUTCOME**
Media player play button is not in an active state. Clicking on the play button does not start the mp3.

**Comment by acozine** [comment]
Presumed related to #114. Closing as resolved.
