### ISSUE TITLE
Remove Users link from menu if user does not have privileges

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#121]
As an editor/admin of Press 1, I should only be able to see a "Manage Users" link for Press 1. I should not be able to see the "Manage Users" link for any other presses.

Note: Some of these acceptance criteria might already be met, but we should make sure to have specs in place to test all cases.

**ACCEPTANCE CRITERIA**

As an admin of a press...
- [ ] ... when I visit the catalog page for that press, I should see the "Users" link in the menu (the link to manage user roles for this press).
- [ ] ... when I visit the catalog page for a different press (that I'm not an admin for), I should not see the "Users" link.

As an editor of a press...
- [ ] ... when I visit the catalog page for any press (even a press that I'm a member of), I should not see the "Users" link.

As a platform-wide admin...
- [ ] ... when I visit the catalog page for any press, I should see the "Users" link in the menu.

**Comment by val99erie** [comment]
I grabbed this story because I'm going to be re-working the press show page, which would clobber any work done for this story.

**Comment by val99erie** [comment]
I re-wrote the acceptance criteria based on the new UI.
