### ISSUE TITLE
Decide how to handle subdomains in local development environments

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#122]
**ISSUE**
When I'm running my development or test environment, I may eventually want to test the press subdomains, giving me something like http://psu.localhost which doesn't resolve by default

**OPTIONS**
1. Set up entries in the local hosts file
2. Run apache & passenger in our development environments
3. Ignore the issue (probably bad from a test-suite perspective)
4. Something else

**ACCEPTANCE**
- [ ]  Jon, Val, Alicia, and Mark discuss and decide on a solution

**Comment by mark-dce** [comment]
See http://shapeshed.com/developing-subdomain-rails-sites-locally/ for additional background o options 1 & 2

**Comment by acozine** [comment]
Looks like setting up virtual hosts is possible in webrick: https://gist.github.com/jvmvik/9d5ae6b6a03487ba6f47 - we could explore that approach.
