### ISSUE TITLE
Add visual indication of which press I'm working on for user permission

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#125]
**STORY**
As a press administration, I would like a visual reminder (logo or words) what press I'm working on, so I know I'm in the right place if I have access to multiple presses.

**ACCEPTANCE**
- [ ] the view for #{press}/users shows the press name (and/or logo) on the page.

**Comment by sethaj** [comment]
Work from story #94 completes this, so there's nothing to do.

**Comment by val99erie** [comment]
This story is for the user roles page, not the press catalog page, so it still needs to be done.  I'll re-open the story.
