### ISSUE TITLE
Create a skeleton importer

### ISSUE THREAD

**Issue by acozine** [curationexperts/heliotrope#127]
Import a monograph with title, author, filename. Potentially add one or two more fields.

**Comment by jmcglone** [comment]
Current template, still in draft form is here:

https://docs.google.com/spreadsheets/d/1XWq47CjafCeGIqNewPODVhJDBMLFf149aypQSr-5I5w/edit#gid=1726739743

**Comment by mark-dce** [comment]
The user imports a monograph from the command line using a CSV file.  At the start of the import, the user specifies the press.

The monograph level metadata should include:
- [ ] Title
- [ ] Author
- [ ] Visibility
- [ ] Files
    - [ ] file_name
    - *first pass, files inherit visibility of main monograph

**Comment by val99erie** [comment]
How to run the importer:
https://github.com/curationexperts/heliotrope/wiki/Import-records-from-CSV-files
