### ISSUE TITLE
NoMethodError in CurationConcerns::Sections#show

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#129]
**STEPS TO REPRODUCE**
1. Login as a privileged user
2. Create a new monograph, set visibility=Open Access
3. Create a new section (visibility=Private)
4. Log out
5. Log in as a different user
6. Find and view the newly created monograph
7. Click the link for the new section 

**ERROR**
```
NoMethodError in CurationConcerns::Sections#show
Showing /Users/mark/.rvm/gems/ruby-2.3.0@heliotrope/bundler/gems/curation_concerns-8f190ff6e93f/app/views/curation_concerns/base/unauthorized.html.erb where line #2 raised:

undefined method `human_readable_type' for nil:NilClass
Extracted source (around line #2):
1
2
3
              
<h1>Unauthorized</h1>
<p>The <%= curation_concern.human_readable_type.downcase %> you have tried to access is private<p>
<p>ID: <%= curation_concern.id %>

Rails.root: /Users/mark/Documents/workspace/_no_backup/RubymineProjects/heliotrope
```

**Comment by sethaj** [comment]
Adding:
``` 
 def curation_concern
    @curation_concern ||= ActiveFedora::Base.find(params[:id])
  end
```
to `app/controllers/curation_concerns/sections_controller.rb` fixes this bug,  but I'm not sure if it's the right thing to do, need to think about it and investigate more.

**Comment by sethaj** [comment]
I guess I'm ok with this solution for now. Wrote a failing test, made the change and the test passes. The PR #171
