### ISSUE TITLE
Sections are displaying incorrect information

### ISSUE THREAD

**Issue by val99erie** [curationexperts/heliotrope#135]
This behavior appeared after the curation_concerns upgrade.  I'm not sure if it's related.

Steps to reproduce the problem:
* Create a monograph using the UI
* Create 2 sections on that monograph (chapter 1 and chapter 2)
* Visit the monograph show page
* When I click the link for chapter 1, it displays chapter 2 info.  Chapter 2 also displays chapter 2 info.

The sections appear to be correct in fedora, but reindexing the sections doesn't fix the problem.

**Comment by acozine** [comment]
This behavior affects all sections - if you create multiple monographs with multiple sections, all sections in all monographs display content from the most recently-created section.

**Comment by val99erie** [comment]
I suspect this might be a problem with the ordered_member_docs method in the MonographPresenter

**Comment by val99erie** [comment]
Hint:  The search in the curation_concern_from_search_results method seems to be returning 3 solr documents instead of 1, and then the method returns the first one in the list, which is the wrong one.  I'm guessing the solr query is missing the ID somehow.
