### ISSUE TITLE
Test support for diacrititcals

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#151]
**TASK**

Test support for diacriticals and non-English data in metadata template

**ACCEPTANCE CRITERIA**
- [x] When a metatdata template with non-English content is uploaded the importer works as intended.

**Comment by val99erie** [comment]
This should be covered by this spec:
https://github.com/curationexperts/heliotrope/blob/master/spec/lib/import/csv_parser_spec.rb#L31
