### ISSUE TITLE
Test support for non-English characters in file names

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#152]
**ISSUE** 

Test support for file names in the metadata template with non-English or special characters. 

**ACCEPTANCE CRITERIA**
- [x] When a metatdata template including a file name with non-English or special characters is uploaded, the importer works as intended, and the file opens and is readable within the UI.

**ADDITIONAL INFORMATION**
- [ ] Check import of number 11 in Northwestern metadata sample template
- [x] Check import of A10, file name with non-English characters

**Comment by val99erie** [comment]
In the 'additional information' section, it talks about number 11.  I'm not sure what that requirement is meant to be.  There are no non-English characters in A11.  But I ran the importer with a filename like A10, and it works fine.
