### ISSUE TITLE
Platform admin can manage monographs created by other users.

### ISSUE THREAD

**Issue by val99erie** [curationexperts/heliotrope#165]
Background info about the intended user abilities for heliotrope:
https://docs.google.com/spreadsheets/d/1D-tFBPzW50InN3qPnZzNScihgbsIQO87DO0mWfNlptg/edit#gid=1442564538

ACCEPTANCE CRITERIA:
- [x] A platform-level admin user can read a monograph created by another user
- [x] A platform-level admin user can update a monograph created by another user
- [x] A platform-level admin user can destroy a monograph created by another user
- [x] A platform-level admin user can publish a monograph created by another user
- [x] A normal logged in user (non-admin) **cannot** update a monograph created by another user
- [x] A normal logged in user (non-admin) **cannot** destroy a monograph created by another user
- [x] A normal logged in user (non-admin) **cannot** publish a monograph created by another user

Note: For a non-admin user, we'll leave the read scenario for another story, since it might be complicated.  It will depend on visibility & publish status, which we haven't fully defined yet.

**Comment by val99erie** [comment]
Check out: `spec/models/ability_spec.rb` and `app/models/ability.rb`

**Comment by sethaj** [comment]
I've added some specs for the first 4 ACs, they pass.

For the final 3 a "normal logged in user (non-admin)" can't, right now, create/publish/destroy _at all_, either their own monographs or others. And there are already tests for that. So maybe this is done? Or we need to think about what a "normal logged in user (non-admin)" role is, like an Editor or Author maybe?

**Comment by jmcglone** [comment]
I think the definition of a normal logged in user (non-admin) at this point is a general user who signs in. They should not be able to CUD. If there are specs for this already, I would consider this done.

When we get around to dealing with Users and Roles, and actually adding the Editor and Author roles to the app, yes we'll need more specs to test.

**Comment by val99erie** [comment]
@sethaj Ah, yeah, I didn't realize that there were already tests for some of those cases.  There are already tests for update and destroy here.  Maybe you could add a line for publish, just for completeness:

https://github.com/curationexperts/heliotrope/blob/master/spec/models/ability_spec.rb#L124-L125

**Comment by sethaj** [comment]
PR for this is #169
