### ISSUE TITLE
Editing a monograph with a section causes the monograph to be inaccessbile

### ISSUE THREAD

**Issue by sethaj** [curationexperts/heliotrope#174]
### To Reproduce:

1. Create a new monograph without attaching a file
2. Add a section to that monograph
3. Edit the monograph
4. Get redirected to a 404, "The page you were looking for doesn't exist."

It's still in the solr index, you can still see the monograph in search results, but the show page 404s.

**Comment by sethaj** [comment]
Can someone try to reproduce this? Maybe it's just too late on a Friday for me to think straight

**Comment by acozine** [comment]
I just tried this. If I follow your instructions exactly, it works fine. But the first time through instead of editing the monograph, I edited the section, and I noticed that on the edit page the monograph got removed. Is it possible you edited the section instead of the monograph?
The monograph-for-this-section reverting to blank is something we should fix.

**Comment by acozine** [comment]
Hm, nope, I can't reproduce this. In trying to reproduce it, I created three links to the same section in my test monograph: 
![screen shot 2016-04-22 at 4 14 44 pm](https://cloud.githubusercontent.com/assets/879121/14755102/5c400488-08a5-11e6-9264-d1279bd5e1cd.png)

**Comment by acozine** [comment]
Paired up with Seth today. I am able to reproduce this bug on the DCE sandbox with the current tip of master (34a5a78) deployed. When I was unable to reproduce it we had 24191b4 deployed. Gist of the production log when I try to access the monograph:
https://gist.github.com/acozine/3b4c7433b9402945ed08350b359c2f54

**Comment by sethaj** [comment]
I've looked into this some more. The key seems to be that on a Monograph edit page, there's a dropdown menu called "Representative Media". Currently it's populated with both Sections and FileSets. If the Monograph has no representative file (so no FileSets), then one of the Sections will be the default. When the edit is saved, the section's id is now the monograph's representative id. But a Section is not a FileSet so I guess bad things happen.

We can override CC's defaults and only let a Monograph's FileSets, not Sections, be in this Representative Media dropdown. 

* But do we want this?

* Do we want to include all of the Monograph's Section's FileSets as an option, not just the Monograph's FileSets?


Maybe something like this in `/app/forms/curation_concerns/monograph_form.rb`

```
    def select_files
      # We only want FileSets here, not Sections
      # Use model.file_set_ids, not model.member_ids
      file_sets ||=
            PresenterFactory.build_presenters(model.file_set_ids, FileSetPresenter, current_ability)
      Hash[file_sets.map { |file| [file.to_s, file.id ] }]
    end
```

**Comment by sethaj** [comment]
I think for this bug it's ok to punt on the larger question, we can always make a new story later. For now only the Monographs's files (FileSets) will be in the Representative Media drop down.
