### ISSUE TITLE
Edit default Vagranfile resources

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#184]
Set the memory and CPU settings lower in the default Vagrantfile: https://github.com/curationexperts/heliotrope/blob/master/Vagrantfile#L65-L66

**Comment by conorom** [comment]
If memory serves (ha!), 1024MB RAM fails to run the three servers (Solr won't have enough RAM to start). I just tested properly and the box uses ~1.4GB when running these and nothing else. I'll give it 1792MB for now to leave some wiggle room. I think the CPU's can be left at 2 to keep the box from being horribly slow. Every PC has two cores and VBox will take only the cycles it needs, as opposed to RAM which is fully reserved.
