### ISSUE TITLE
Creator field is overwritten with logged in user's e-mail address when creating or updating FileSet record

### ISSUE THREAD

**Issue by jmcglone** [curationexperts/heliotrope#188]
When creating or updating a File Set/Asset record and supplying a name in the creator field, the creator field is overwritten with the logged in user's e-mail address.

## To Replicate

1. Create a monograph
2. Attach a File
3. On the File Set metadata page, add a title, upload a file, and give it a creator. Save the form.
4. View the File Set show page. The creator should display as the user's e-mail address.

There is already a (commented out) test for this in https://github.com/curationexperts/heliotrope/blob/master/spec/features/create_file_set_spec.rb#L49

**Comment by val99erie** [comment]
See also:  #233
