### ISSUE TITLE
Implement resque-web mounted in application

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#197]
**STORY**
As a platform or press administrator, I would like an easy way to view background jobs, so that I can verify queues are being processed correctly.

**DETAILS**
See the instructions for mounting resque-web as an engine here: https://github.com/resque/resque-web#starting

Adapt the instructions for restricting access here: https://github.com/resque/resque-web#starting
We'll need to modify the code to match our authorization scheme for admins.

**ACCEPTANCE**
- [x] As a platform admin, I can view the resque-web interface from my browser at \<host\>/resque
- [ ] ~~As a press admin, I can view the rescue-web interface from my browser~~
- [ ] ~~As a press editor, I get an error message saying the page does not exist~~
- [x] As any other logged in user, I get an error message saying the page does not exist
- [x] As an unauthenticated user, I get a message asking me to log in.
- [x] As a platform admin, I have a link to the resque-web URL

**Comment by acozine** [comment]
First acceptance met by PR #208. I'm taking my name off this ticket and tossing it back into Ready.

**Comment by val99erie** [comment]
@mark-dce Should a press-level admin really have access to resque?  That will allow them to view/delete/cancel/re-run jobs at other presses, and may expose data from other presses.

**Comment by mark-dce** [comment]
At some point, the Michigan folks will need to decide if press-level admins should have full access, some kind of constrained access, or no access.  Ideally press-level admins would have access to jobs for their press, but not other presses, but I think it's a pretty big piece of work to make that work (you might need individual queues per press or to somehow namespace jobs by press, etc.)

It's 50/50 to me whether press-level administrators get the same access as platform-level administrators or whether they're restricted the same way press editors are.  I put the requirement in to ensure we addressed the access one way or another, but I'm totally ok if denying access is simpler.

**Comment by jmcglone** [comment]
I agree it would be great if a press-level admin could have access to just
their jobs -- but for now I think it would be okay to deny access.

Curious if the kind of functionality Mark describes would be something
hy-box folks tackle with multi-tenancy?

On Thu, May 5, 2016 at 9:47 PM, Mark Bussey <notifications@github.com>
wrote:

> At some point, the Michigan folks will need to decide if press-level
> admins should have full access, some kind of constrained access, or no
> access. Ideally press-level admins would have access to jobs for their
> press, but not other presses, but I think it's a pretty big piece of work
> to make that work (you might need individual queues per press or to somehow
> namespace jobs by press, etc.)
>
> It's 50/50 to me whether press-level administrators get the same access as
> platform-level administrators or whether they're restricted the same way
> press editors are. I put the requirement in to ensure we addressed the
> access one way or another, but I'm totally ok if denying access is simpler.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/curationexperts/heliotrope/issues/197#issuecomment-217328619>
>



-- 
Jon McGlone
Front End Developer & UI Designer
Michigan Publishing
University of Michigan Library
734-763-4260
publishing.umich.edu <http://www.publishing.umich.edu>

**Comment by jgmorse** [comment]
Agree to just deny access to press-admins.

On Fri, May 6, 2016 at 8:57 AM, Jonathan McGlone <notifications@github.com>
wrote:

> I agree it would be great if a press-level admin could have access to just
> their jobs -- but for now I think it would be okay to deny access.
>
> Curious if the kind of functionality Mark describes would be something
> hy-box folks tackle with multi-tenancy?
>
> On Thu, May 5, 2016 at 9:47 PM, Mark Bussey <notifications@github.com>
> wrote:
>
> > At some point, the Michigan folks will need to decide if press-level
> > admins should have full access, some kind of constrained access, or no
> > access. Ideally press-level admins would have access to jobs for their
> > press, but not other presses, but I think it's a pretty big piece of work
> > to make that work (you might need individual queues per press or to
> somehow
> > namespace jobs by press, etc.)
> >
> > It's 50/50 to me whether press-level administrators get the same access
> as
> > platform-level administrators or whether they're restricted the same way
> > press editors are. I put the requirement in to ensure we addressed the
> > access one way or another, but I'm totally ok if denying access is
> simpler.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/curationexperts/heliotrope/issues/197#issuecomment-217328619
> >
> >
>
>
>
> --
> Jon McGlone
> Front End Developer & UI Designer
> Michigan Publishing
> University of Michigan Library
> 734-763-4260
> publishing.umich.edu <http://www.publishing.umich.edu>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/curationexperts/heliotrope/issues/197#issuecomment-217431512>
>



-- 
Jeremy Morse
Director of Publishing Technology
Michigan Publishing
734.615.5739
