### ISSUE TITLE
bin/setup script to setup development environment

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#2]
**Description**
As a developer, I want to be able to start a development server on my machine.  All the default configuration / seed data should be copied into place when I type `bin/setup` so that I can next type `rails server` and have a working application running

**Acceptance criteria**
- [ ]  `bin/setup` copies all configuration templates.
- [ ] runs `rake db:migrate`
- [ ] runs `rake db:seed`

**Comment by mark-dce** [comment]
**ADDITIONAL ACCEPTANCE CRITERIA**
- [ ] After I run `bin/setup`, I can run `rails server` and access the application at localhost:3000
