### ISSUE TITLE
Play audio asset

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#20]

**Comment by acozine** [comment]
Now that #114 and #117 are resolved, adding acceptance:

##Acceptance:
- [ ] Curation Concerns behavior for audio files fulfills Michgan Press expectations.

**Comment by shanitajohn** [comment]
Stale ticket, closing it out since we demoed this at the end of our 3rd sprint: 

Agenda here:
https://docs.google.com/document/d/1XG_Z0TURBj_rUGu69eAJ_4zPQmpiN15AdllbVnUEFrQ/edit
