### ISSUE TITLE
Play video asset

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#21]

**Comment by acozine** [comment]
I believe this ticket can be closed. Today I uploaded a video file, it transcoded correctly, a thumbnail was created, and I was able to play it back.

**Comment by acozine** [comment]
I believe this ticket can be closed. After setting `config.enable_ffmpeg = true` in config/initializers/curation_concerns.rb via https://github.com/curationexperts/heliotrope/pull/113, I can upload a video file, it transcodes correctly, a thumbnail is created, and I can play it back.

**Comment by mark-dce** [comment]
Re-opening this ticket for final Michigan review (along with audio, images, etc.) to ensure that the basic curation concern function meets their needs.  If so, we'll close the ticket, if not, we all acceptance criterial based on their feedback.

**Comment by acozine** [comment]
Per demo discussion 3/30/16, video playback is okay.
