### ISSUE TITLE
Viewing an asset

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#212]
When I resolve a URI for an asset in my browser: (This might just be the FileSet show page)

**ACCEPTANCE CRITERIA**
- [ ] I should see a page that contains the web-viewable version of asset.
- [ ] I should see a link to download the original asset (assuming I have permission to download it).
- [ ] I should see information about which monograph and section(s) this asset belongs to. (hold for future)
- [ ] When I view a clone from a specific section, I should get an indication of the other sections the asset is included in. - see the wireframe http://mlibrary.github.io/elderberry/press/book/item/video.html

**Comment by shanitajohn** [comment]
**QUESTIONS**
- [ ] I should see the metadata for the asset. (Question: What happens if we decide that the metadata can be different in different sections?  Do we show all metadata for all sections?  Or maybe just show minimal metadata with links to more specific show pages that will have the rest of the metadata?)

When I navigate to the show page for an asset from a section or monograph:

**QUESTIONS**
- [ ] If I click a link to an asset from a certain section, and I'm viewing a page for that clone, should the page contain information about the other section(s) that the asset is also attached to?

**Comment by val99erie** [comment]
These are all covered in other stories #202, #203, #204, #205.
