### ISSUE TITLE
Search by title, author, subject

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#23]

**Comment by shanitajohn** [comment]
Acceptance criteria

- [ ] When you type a title, author or subject into the main search box, the search results returned contain the correct title author or subject

**Comment by jcoyne** [comment]
Exact match or partial match?  If partial, by English stemming or N-Grams?

**Comment by jcoyne** [comment]
Also, we don't have a field called "Author", is there a missing story or do you mean "Creator"?

**Comment by mark-dce** [comment]
* Partial match
* English stemming on titles and subjects (unless n-grams is easier, then n-grams)
* No stemming on creators
* Whitespace and punctuation tokenization on author and title: 'mark' should match 'Bussey, Mark' and 'Marks of distinction: fine English silver'
* Allow wildcards: 'bus*' should match 'bussey'

*if any of this is more difficult than another alternative, implement the simpler alternative and document the behavior*
