### ISSUE TITLE
Facet by subject

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#24]

**Comment by shanitajohn** [comment]
Acceptance criteria

- [ ] On catalog or search results page when user selects a subject from the facet list the search results should only show the objects associated with that subject.

- [ ] Objects that don't have that subject should not be in the list

- [ ]  When the user does a search, the subjects that appear in the facet list should match the subjects of the objects in the search results

- [ ]  The subjects in the facts list should have an accurate count

**Comment by mark-dce** [comment]
This story should include a feature test or two in the code
