### ISSUE TITLE
One fedora vs. multiple 

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#45]
How will other Hydra Heads & other fedora clients  ensure they don't expose press items they shouldn't

How will the press ensure it doesn't expose non-press items.

**Comment by mark-dce** [comment]
* How do you ensure a bug in code in another application (like deep blue) doesn't negatively impact press content
* How do ensure a re-index of other content doesn't impact the press content & vice versa
* How is capacity managed across applications & how do you isolate applications from a fedora performance perspective
* Where are access policies enforced (how do external press users get defined?)
