### ISSUE TITLE
Collect sample press "buy now" links

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#46]
What do the various press "buy now links" look like?

**Comment by mark-dce** [comment]
**ACCEPTANCE**
- [ ] One or more sample "Buy Now" links for *existing* monographs on each press site.

**Comment by jmcglone** [comment]
UM Press - http://www.press.umich.edu/3156987/silent_hill

**Comment by shanitajohn** [comment]
Another UM Press example: 
https://www.upress.umn.edu/book-division/books/north-shore

Northwestern example:
http://www.nupress.northwestern.edu/content/directors-prism

In future Northwestern would like to use a URL like this Amazon example:
http://www.amazon.com/Directors-Prism-Hoffmann-Theatrical-Avant-Garde/dp/0810133563/

**Comment by mbakeryo** [comment]
Penn State example (for Volume 2): http://www.psupress.org/books/titles/978-0-271-07576-1.html

**Comment by mbakeryo** [comment]
Indiana example: 
http://www.iupress.indiana.edu/product_info.php?products_id=808132?
