### ISSUE TITLE
Which domain format should be used? 

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#48]
Do they have a domain to use like digitalpress.org?

Opt 1: digitalpress.org/press_name
Opt 2: press_name.digitalpress.org/

(If they don't have a name like digitalpress.org)
Opt 3: digital.umich.edu/press_name
Opt 4: press_name.digital.umich.edu

**Comment by mark-dce** [comment]
Prefer the subdomain model (option #2):
press_name.digitalpress.org/
