### ISSUE TITLE
Order Sections within a Monograph

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#50]
**STORY**
As a press user, I would like to be able to order sections within a monograph, so that I can reflect the ordering and structure of the primary narrative in the UI for accessing associated assets.

**NOTES**
For the first pass, do the simplest possible thing.  This will facilitate having a more detailed discussion about refinements like drag-and-drop vs. assigning order numbers, etc.

**ACCEPTANCE**
- [x] I can re-arrange the order of sections within a Web UI

**Comment by val99erie** [comment]
If you click the "File Manager" button, you can reorder all the sections and assets that are attached to the monograph by using the drag and drop functionality.

**Comment by val99erie** [comment]
Now that the user roles are in, you can't just create monographs anymore.  Here's what you'll need to do to test this story:

Run this rake task to create the super admin user:
rake admin

And make sure redis is running.

Then you can log into the UI with that user and create a monograph with sections and files attached.  At the bottom of the monograph show page, click "File Manager" (we should change the name of that button), and you should be able to reorder the files and sections.

The re-ordering won't take effect unless you click the 'Save' button.

Then when you go back to the monograph show page, the files and sections are each listed separately, but each list should be in the correct order.

We'll probably change how these lists are displayed at some point (like maybe they won't be in separate lists), but this was just a first pass.
