### ISSUE TITLE
Update production  & demo configuration management scripts to deploy for Solr 5.0

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#51]
**ACCEPTANCE**
- [ ] Demo & production environments use Solr 5.0

**Comment by acozine** [comment]
See https://github.com/curationexperts/ansible-hydra/pulls for a first iteration toward this goal.

**Comment by acozine** [comment]
Michigan is testing the ansible scripts now. PR for Solr 5 changes here: 
https://github.com/curationexperts/ansible-hydra/pull/114
leaving this ticket open pending a successful test and/or merging the PR.
