### ISSUE TITLE
Implement the initial metadata fields for a File

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#54]
**DETAILS**
This is the implementation story that correlates with #11

**ACCEPTANCE**
- [x] Any new fields are implemented in the metadata code.
- [x] Fields are displayed on the File show page
- [x] Field contents can be edited in the File edit view.

**Comment by jmcglone** [comment]
@val99erie I can meet the acceptance criteria, however I'm seeing upon first creation of a new FileSet that the creator field is getting overwritten with the uploader's e-mail address/username. Further refactoring needs to be done to allow for multiple values and validation.

**Comment by val99erie** [comment]
@jmcglone Let me look into that.  It might be that creator is a reserved field for curation_concerns (meaning that it might be used for access controls).  Let me check on that before we override that behavior.
