### ISSUE TITLE
Determine preliminary series metadata

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#55]
**STORY**
As a user, I would like to see descriptive metadata fields for a series, so that I can understand the context of what I'm viewing.

**ACCEPTANCE**
- [x] There is an initial list of field names that should be shown on the monograph detail page
- [x] There is an RDF predicate selected for each field
- [x] Cardinality of fields is listed for each field (i.e. can each field have multiple values, only a single value, or can it be left blank)
- [x] List data type for each field (eg. string, date, integer, decimal, controlled)
- [x] List any validations specific to any fields

**Comment by mark-dce** [comment]
We should figure out if there are any series fields that need to be added to the basic monograph descriptive metadata (#8 & #53).  Ideally this would be additive in terms of the actual metadata model - but we wouldn't have to show all fields if there were basic monograph fields that didn't make sense for a series.  (or maybe refactor both to a basic metadata set (title + ?) and then supplemental metadata specific to the object class (monograph or series or sub brand)

**Comment by jmcglone** [comment]
Series metadata on the "Series" sheet at https://docs.google.com/spreadsheets/d/1Xzod0SL-Dev1Bh5TklU0OuvSsQhErfG_huDP3dpLcPo/edit

**Comment by jmcglone** [comment]
I have added columns to indicate if the field should use existing basic_metadata or monograph_metadata

**Comment by jmcglone** [comment]
FWIW, I did not see a implement series metadata story during our sprint planning earlier today
