### ISSUE TITLE
Include two sub-domains on sandbox

### ISSUE THREAD

**Issue by acozine** [curationexperts/heliotrope#56]
We are heading for a model where each press has a subdomain (umichpress.ourplatform.org, indianaupress.ourplatform.org), make sure the sandbox has at least two sub-domains.

**Comment by jcoyne** [comment]
All three domains (ourplatform.org, umichpress.ourplatform.org and indianaupress.ourplatform.org) should all route to the same rails application.

**Comment by acozine** [comment]
http://pennstate.press.curationexperts.com/
http://umich.press.curationexperts.com/
http://indiana.press.curationexperts.com/
