### ISSUE TITLE
Can't create new monograph

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#67]
**STEPS TO REPRODUCE**
On the demo system at http://press.curationexperts.com
1. Login to the application
2. Click on "+" and select "Add a new work / New Monograph"
3. Enter a title
4. Click on the "Create Monograph" button

**EXPECTED RESULT**
A new monograph is created and I am sent to the view page for it.

**ACTUAL RESULT**
We're sorry, but something went wrong.

**Comment by jmcglone** [comment]
I get the same error following those steps on http://press.curationexperts.com

However, based on the "Add New Monograph" view page (which lacks initial Monograph fields I've added, like the ISBN), this instance seems to be outdated. On my local machine with the latest copy of the repository, I do not get this error following those same steps.

**Comment by mark-dce** [comment]
Shoot, I should have checked we have current code deployed first (we don't).  I'm redeploying and will test again.

**Comment by mark-dce** [comment]
I've deployed the current head of master (c75aee7427b9bc3eab2f03dcd103a997a30b4a5d) and I'm still seeing the same behavior.

**Comment by mark-dce** [comment]
Potentially caused by #69 - marking as blocked until that ticket is resolved.

**Comment by jcoyne** [comment]
I can no longer repeat this.

**Comment by jcoyne** [comment]
#69 is closed, so unblocked.
