### ISSUE TITLE
Blank search doesn't work

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#68]
**STEPS TO REPRODUCE**
On system here: http://press.curationexperts.com/
1. login to application
2. click on magnifying glass next to search box

**EXPECTED RESULT**
I would see a page that displays all content within the repository 

**ACTUAL RESULT**
I received a message that said, "Sorry, I don't understand your search."

**Comment by acozine** [comment]
Solr 5 had incorrectly configured cores. 
New core is called umichpress. Content is at /var/solr/data/umichpress.
