### ISSUE TITLE
Share config directory across deployments

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#69]
**ISSUE**
I had to manually edit role_map.yml for the application to load correctly after a cap deploy.  I'm not sure what other configuration I might be missing.

**Comment by mark-dce** [comment]
Solr is also indicating that no cores are configured

**Comment by acozine** [comment]
Re: config - the directory isn't shared, only specific files. I noticed the issue with role_map.yml on 3/8 and then didn't follow up: see https://curationexperts.slack.com/archives/general/p1457470689000093 - my current thinking is that role_map.yml should have a production section added and also be a shared file for capistrano - what do others think?

**Comment by jcoyne** [comment]
I do not think it should be a shared file. Why do you think it should be shared?

**Comment by acozine** [comment]
Deployed as is, it breaks the system. I considered checking in a copy with a production section that lists the logins we use for admin roles, but that sounds like a bad precedent for security. It would expose the logins we use on the sandbox, and it might encourage others to copy those settings in production elsewhere. My suggested solution is that we check in a copy with a sample production section, then share the file in Cap to protect the actual production credentials. How would you prefer to handle it?

**Comment by mark-dce** [comment]
If we're using a configuration management tool like ansible, chef or puppet to manage deployment environments, shouldn't we be letting that tool manage the config files appropriate to the particular server (and just sharing the config directory across deployments)

Specific to role_map.yml - why would we need to put actual logins in - all the others are dummy values.  Why can't we use admin@example.com.  Do we even need a value in that section or or can we just add a blank production section?

**Comment by acozine** [comment]
My suggested solution (add a dummy production section to the file in Github and make the production file a Capistrano shared file for the actual production values) was based on my theory that role_map.yml controls AuthZ using roles as long as we continue to use Devise.

Have I misunderstood what role_map.yml does or should do?

**Comment by acozine** [comment]
Per discussion, we will use dummy settings.
