### ISSUE TITLE
Deleting a monograph should delete all its sections

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/heliotrope#76]

**Comment by shanitajohn** [comment]
Closing this ticket. I tested the functionality and it works.

**Comment by mark-dce** [comment]
**STEPS TO REPRODUCE**
1) Create a new monograph and note it's ID and URL
2) Create a new section and note it's ID and URL
3) Delete the monograph through the UI
4) Try to access the monograph via it's URL from step 1
    *EXPECTED BEHAVIOR* You should get a "The page you've requested does not exist" or similar error message-
    *ACTUAL BEHAVIOR*  right now you get "something went wrong" - see #180 for that issue  
5) Try to access the section via it's URL from step 2
    *EXPECTED BEHAVIOR* You should get a "The page you've requested does not exist" or similar error message
    *ACTUAL BEHAVIOR*  right now you get "something went wrong" - see #180 for that issue  
6) SSH to the server and open a rails console session
7) Search for the monograph using the ID from step 1 - `m = Monograph.find(id)`
8) You should get an `Ldp::Gone: ` error
9) Search for the section using the ID from step 2 - `s = Section.find(id)`
    *EXPECTED BEHAVIOR* You should get an  `Ldp::Gone: ` error because the section should have been deleted
    *ACTUAL BEHAVIOR* the section still exists after the monograph was deleted
