### ISSUE TITLE
Internal server error on unrecognized file type uploads

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#79]
**ISSUE**
When I try to upload a file with a .mscz file extension (MuseScore) in the multiple uploader, I get an 'internal server error' message.

**LOG**
https://gist.github.com/mark-dce/b183a621aad85815c72f

**Comment by val99erie** [comment]
Could you put a sample .mscz file in the /data directory on the demo server?

**Comment by jcoyne** [comment]
`Errno::ENOENT (No such file or directory - soffice):` <- Star office is not installed.

**Comment by mark-dce** [comment]
Tested & no longer occurs  after LIbre office installed on server.
