### ISSUE TITLE
Determine list of initial monograph metadata fields

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#8]
**STORY**
As a user, I would like to see descriptive metadata fields for a monograph, so that I can understand the context of what I'm viewing.

**ACCEPTANCE**
- [x] There is an initial list of field names that should be shown on the monograph detail page
- [x] There is an RDF predicate selected for each field
- [x] Cardinality of fields is listed for each field (i.e. can each field have multiple values, only a single value, or can it be left blank)
- [x] List data type for each field (eg. string, date, integer, decimal, controlled)
- [x] List any validations specific to any fields

**Comment by jmcglone** [comment]
I have a first pass at this for others to comment on / raise questions and concerns here:

https://docs.google.com/spreadsheets/d/1Xzod0SL-Dev1Bh5TklU0OuvSsQhErfG_huDP3dpLcPo/edit
