### ISSUE TITLE
Edit access restrictions on sections

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#81]
**STORY**
I would like to be able to set access restrictions on a section once it has been created.

**ACCEPTANCE**
- [x] New sections default to the access rights of the monograph they're attached to.
- [x] I can change the access restrictions on a section using controls similar to the ones I use to set access restrictions on a monograph.

**Comment by sethaj** [comment]
Part 2 of this sort of cancels out part 1. Adding visibility controls to sections, in the same way as monographs, means having to pick a visibility when adding a new section so not really using a default.

But part 1 can still apply to imported sections. Then the section will default to the same visibility as it's monograph if no visibility is in the spreadsheet for that section.

**Comment by mark-dce** [comment]
@sethaj - what I meant by part 1 was that the dropdown for part 2 would be pre-set with the proper value - you can construct your selection box so that it's set to a value different than the first item in the list. So you need a little dynamic code that determines the monograph access setting and then builds the selection box so it has the same access level set when the page draws.  If that sounds like a good idea, we can open a separate ticket for it.
