### ISSUE TITLE
Configure management scripting for UMich QA environment

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/heliotrope#9]

**Comment by acozine** [comment]
Per discussion with Aaron and Colin, Michigan will manually build servers as needed to accomodate their multi-hydra-head architecture.

**Comment by acozine** [comment]
Acceptance: 
Ansible scripts allow users to 
- [ ] select mysql instead of postgresql
- [ ] select puma instead of passenger
when building a production-style server

**Comment by acozine** [comment]
See https://github.com/projecthydra-labs/ansible-sufia7-playbook
