### ISSUE TITLE
Manually associate a new monograph with a press

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#95]
**STORY**
When I create a new monograph, I would like to be able to associate it with a press, so that it will show up on that press's landing page and facets.

**ACCEPTANCE**
- [x] Users get a list of presses to choose from when creating a monograph (see #97 re list of presses)
- [x] A monograph must be associated with a press
- [x] Update the dev notes description of how to create a monograph:  https://github.com/curationexperts/heliotrope/wiki/Developer-Notes

**Comment by mark-dce** [comment]
Blocked until #97 is complete

**Comment by val99erie** [comment]
@mark-dce Some assumptions I made...

For the predicate of the Press, I used:
http://id.loc.gov/vocabulary/relators/pbl

And curation_concerns already has a predicate for Publisher, which is a multi-value field:
http://purl.org/dc/elements/1.1/publisher

So, I added the new predicate for press, but I didn't change the existing publisher property.
If you want something different, could you write a story with the new predicate info?
