### ISSUE TITLE
Manage list of presses

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#97]
**STORY**
As a platform admin, I need a mechanism to add new presses, so that I can grow our hosting business.

**ACCEPTANCE**
For each press, the system maintains a record of
- [ ] The press name
- [ ] A pointer to the press logo
- [ ] A description of the press
- [ ] The subdomain for the press (ID or short-name)

**Comment by shanitajohn** [comment]
**NOTES**
Assets / images hosted in Rails

**Comment by mark-dce** [comment]
There doesn't need to be a CRUD UI for this, just some way to persist the data and edit it, so that we have the info we need for #93 stored somewhere.
