### ISSUE TITLE
Associate a user with an editor role

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/heliotrope#99]
**STORY**
As a platform admin, I would like to be able to give users press-level editor rights, so they can create and update monographs

**ACCEPTANCE**
As a platform admin, 
- [x] I can see a list of all users
- [x] I can give set the editor role associated with a specific press
- [x] I can give a user editorship at more than one press
- [x] I can revoke editorship for a user at a press

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss/spotlight/blob/master/app/models/spotlight/role.rb for how Spotlight models this.
